# Ustalenia przeliczników i limitów dla graczy
reward:
  points_rate: 1.0

# Ustawienia niezbędnyhc informacji do łaczenia z bazą danych
database:
  # Dostępne opcje: mariadb, mysql TODO: dodać SQLite oraz H2
  type: "mariadb"
  mysql:
    host: "localhost"
    port: 3306
    name: "my_database"
    username: "user"
    password: "password"

# Ustawienia sprawdzania i automatycznej aktualizacji
checkForUpdates: true
autoDownloadUpdates: false