name: My-Coins
version: '${project.version}'
main: pl.mymc.mycoins.My_Coin
api-version: '1.21'
authors: [WieszczY, mxLega]
description: Plugin do nagradzania graczy walutą gry za czas spędzony na serwerze
depend: [EternalCore, Vault]
