name: My-Coins
version: '${project.version}'
main: pl.mymc.mycoins.My_Coin
api-version: '1.20'
authors: [WieszczY, mxLega]
description: Plugin na nagradzanie graczy walutą gry za czas spędzony na serwerze
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
