name: My-Coins
version: '${project.version}'
main: pl.mymc.mycoins.My_Coin
api-version: '1.20'
authors: [WieszczY]
description: Plugin na nagradzanie graczy walutą My-Coins za czas spędzony na serwerze
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
